spring:
  datasource:
    url: jdbc:mysql:aws://SERVER-ADDRESS:3306/plates?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: plates
    password: plates!Q@W#E4r
    driver-class-name: software.aws.rds.jdbc.mysql.Driver
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 30
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      data-source-properties:
        rewriteBatchedStatements: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  config:
    activate:
      on-profile: dev
    import: oauth2.yml

#logging:
#  level:
#    org.hibernate.SQL: debug
##org.hibernate.type: trace
#
logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    reactor:
      netty:
        http:
          client: trace

plate:
  jwt:
    secret: R5f1j5x4T5wZBs5rXWK1mKXl8Ig=

